version: "3.9"
services:
  dev-container:
    build:
      dockerfile: ./.devcontainer/Dockerfile
      context: ./
    volumes:
      - .:/workspaces/west-end-financial:cached
      - ~/.docker/config.json:/root/.docker/config.json:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: /bin/sh -c "while sleep 1000; do :; done"
