name: wf-cd-acmebot-prod

env:
  DOCKERHUB_ID: 'armck'
  CONFIGURATION: 'acmebot'
  ENVIRONMENT: 'prod'

on: 
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  setup-env:
    runs-on: ubuntu-24.04
    outputs:
        dockerhub_id: ${{ steps.env.outputs.dockerhub_id }}
        configuration: ${{ steps.env.outputs.configuration }}
        environment: ${{ steps.env.outputs.environment }}
    steps:
      - name: Setup environment variables
        id: env
        run: |
          echo "dockerhub_id=$DOCKERHUB_ID" >> "$GITHUB_OUTPUT"
          echo "configuration=$CONFIGURATION" >> "$GITHUB_OUTPUT"
          echo "environment=$ENVIRONMENT" >> "$GITHUB_OUTPUT"

  terraform-deployment-ci:
    needs: setup-env
    uses: armckinney/cicd/.github/workflows/rwf-terraform-deployment-ci.yaml@main
    with:
      # using standard container image for deployment as opposed to devcontainer
      container_image: armck/terraform-azure:2.73.0
      configuration: ${{ needs.setup-env.outputs.configuration }}
      environment: ${{ needs.setup-env.outputs.environment }}
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
